### ISSUE TITLE
Bug: date-fns not found after upgrading to @xmtp/react-sdk@2.0.0

### ISSUE THREAD

**Issue by fabriguespe** [xmtp/xmtp-web#115]
### Describe the bug

After upgrading to @xmtp/react-sdk@2.0.0, a module not found error is encountered preventing the application from functioning correctly.

```bash
Module not found: Error: Can't resolve 'date-fns/min' in '/Users/fabrizioguespe/DevRel/my-app/node_modules/@xmtp/react-sdk/lib'
Did you mean 'index.js'?
BREAKING CHANGE: The request 'date-fns/min' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

### Steps to reproduce the bug

To Reproduce

- `create-react-app` fresh install
Or clone this repo with the packages imported already and with polyfill [create-react-app-xmtp-react-sdk-2](https://github.com/fabriguespe/create-react-app-xmtp-react-sdk-2).
- Upgrade to @xmtp/react-sdk@2.0.0
- `npm install`
- `npm run start` or `npm run build`
- See error

### Additional context

- Node version: v18.16.1
- Running npm install date-fns does not resolve the issue.

**Comment by rygine** [comment]
this was resolved by https://github.com/xmtp/xmtp-js/pull/477
