### ISSUE TITLE
`message.contentType` is a string but `codecFor` expects an object

### ISSUE THREAD

**Issue by fabriguespe** [xmtp/xmtp-web#206]
### Describe the bug

In the reactSDK (as well as in the JS SDK) `codecFor` expects a contenType object.

```
/**
 * Find a matching codec for a given `ContentTypeId` from the
 * client's codec registry
 */
codecFor(contentType: ContentTypeId): ContentCodec<any> | undefined;
```

Yet in the reactSDK the `message.contentType` returns a string, making `codecFor` return `undefined`

This is how it looks in react
![CleanShot 2024-02-28 at 15 11 34@2x](https://github.com/xmtp/xmtp-web/assets/1447073/f178bae1-586f-4246-a7eb-fb86d5b80c5a)

This is how it looks in js
![CleanShot 2024-02-28 at 14 57 13@2x](https://github.com/xmtp/xmtp-web/assets/1447073/5af1df21-51e9-4f16-9f1e-5771309fe081)

**Comment by rygine** [comment]
thanks for reporting this! yes, in the React SDK, we use/store `contentType` as a string. to convert back to an object for use in `codecFor`, use the `ContentTypeId.fromString` static method.

```ts
const contentType = ContentTypeId.fromString(message.contentType);
const codec = xmtpClient.codecFor(contentType);
```

**Comment by fabriguespe** [comment]
Thks! Updated the docs snippet 
https://github.com/xmtp/xmtp-dot-org/pull/680
