### ISSUE TITLE
Bug: DexieError after upgrade to latest xmtp sdks

### ISSUE THREAD

**Issue by doktordos-eth** [xmtp/xmtp-web#215]
### Describe the bug

Upgraded to latest xmtp react and js sdks and get the following errors everytime i sign in to xmtp.
![Screenshot 2024-03-18 085950](https://github.com/xmtp/xmtp-web/assets/80520453/ea821bc8-d368-40f3-b535-c2b5339717f1)
![Screenshot 2024-03-18 090100](https://github.com/xmtp/xmtp-web/assets/80520453/f10d3742-d3c5-4baa-b567-bac4c919a7c1)
After manually deleting the indexed db all works as expected-

### Expected behavior

No dexie errors are thrown from the sdks - schema mismatches should be handled internally without needing to manually delete the indexed db ..

### Steps to reproduce the bug

upgraded from react-sdk 4.0.0 to 5.2.0 and js-sdk 11.1.1 to 11.5.0

**Comment by rygine** [comment]
hey @doktordos-eth! thanks for the report. it's not necessary to delete the DB, but rather just increase the schema version. sorry that this wasn't clear in our docs.

in #219, i added a schema check that will throw an error when there's a schema mismatch and inform app developers to update their schema version. hope this helps, and of course, open to feedback!

**Comment by rygine** [comment]
@doktordos-eth this may be resolved via #284. please re-open if the issue persists after upgrading to the latest SDK.
