### ISSUE TITLE
Feature request: Update documentation for useMessages() hook

### ISSUE THREAD

**Issue by daria-github** [xmtp/xmtp-web#27]
### Is your feature request related to a problem?

This is just a request to add documentation to the useMessages hook around the additional options. It's already included in the type but I think the example could benefit from this additional information as well, since it'll likely be a common usage of this hook (including within our inbox app).

**Comment by rygine** [comment]
this is resolved by https://github.com/xmtp/xmtp-dot-org/pull/582
