### ISSUE TITLE
Bug: readReceiptContentTypeConfig not existing in @xmtp/react-sdk package

### ISSUE THREAD

**Issue by anthony23991** [xmtp/xmtp-web#285]
### Describe the bug

While working on @xmtp/react-sdk package using the 7.0.1 version, when initializing the provider and adding the contentTypeConfigs, the readReceiptContentTypeConfig does not exists in the package to enable read receipt in my app, it is throwing an error when calling it the same way as the documentation:
'"@xmtp/react-sdk"' has no exported member named 'readReceiptContentTypeConfig'
I was using the js sdk and it was working fine, but when changing to the react sdk its not working.

### Expected behavior

The 'readReceiptContentTypeConfig' contentTypeConfig should be imported from the react-sdk as shown in the documentation: https://xmtp.org/docs/build/messages/read-receipt

### Steps to reproduce the bug

1. Install these packages in your package.json:
"@xmtp/content-type-primitives": "^1.0.1",
        "@xmtp/content-type-reaction": "^1.1.9",
        "@xmtp/content-type-read-receipt": "^1.1.10",
        "@xmtp/content-type-remote-attachment": "^1.1.9",
        "@xmtp/content-type-reply": "^1.1.11",
        "@xmtp/content-type-text": "^1.0.0",
        "@xmtp/react-sdk": "7.0.1",
        "@xmtp/xmtp-js": "^12.0.0",
2. Place the provider in the app.tsx and try to import the readReceiptContentTypeConfig from @xmtp/react-sdk

**Comment by rygine** [comment]
hey @anthony23991! sorry about the confusion here. our docs were out of date and have now been corrected. the React SDK no longer provides support for read receipts out of the box.
