### ISSUE TITLE
Bug:  `@xmtp/xmtp-js` &  `@xmtp/content-type-remote-attachment` Module not found at `@xmtp/react-sdk`

### ISSUE THREAD

**Issue by happyeric77** [xmtp/xmtp-web#287]
### Describe the bug

The `@xmtp/xmtp-js` &  `@xmtp/content-type-remote-attachment` packages are in `@xmtp/react-sdk`'s `devDependencies` list, but they are used during runtime . It causes the `yarn install` not including these packages in `node_modues`, which causes the `Module not found` error.

> NOTE: If we use `npm install`, it will work because I think NPM also includes the devDependencies in node_modules.

### Expected behavior

Both yarn and npm install should work. I guess we should move those runtime needed packages to `depedencies` from `devDependencies` in `package.json`

### Steps to reproduce the bug

It can be easily replicated by following steps:

1. Cone the repo: https://github.com/happyeric77/xmtp-notifi-example
2. create a `.env.local` file with the following content under root dir

```bash
NEXT_PUBLIC_TENANT_ID='4zfoga0vjqh90ahg8apd'
NEXT_PUBLIC_ENV='Production'
NEXT_PUBLIC_INFURA_API_KEY='9c9ff698105d4f6b9b2b93eddc0dff72'
NEXT_PUBLIC_CARD_ID='90f9ac3f674a4a79955204afc1142a39'
```

3. Run `yarn install` && `yarn dev`

4. Install [metamask browser extension](https://chromewebstore.google.com/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn) and create a new wallet 
5. Access `localhost:3000`
6. Click `metamask` button
![Screenshot 2024-07-23 at 15 23 35](https://github.com/user-attachments/assets/bd19f45d-f02a-4069-b94e-330febc67b7a)

Then the error will be shown like below:
![Screenshot 2024-07-23 at 15 24 48](https://github.com/user-attachments/assets/3e23ae2b-7cb5-4c6a-b4de-5bfaf988bfdf)

> However as mentioned above, if we use `npm install`, it will work fine because those devDepedencies listed in `@xmtp/react-sdk` will be included in `node_modules`

**Comment by rygine** [comment]
hey @happyeric77! sorry for the confusion. the React SDK has several required peer dependencies, which are not automatically installed with `yarn install`.

see the [install](https://github.com/xmtp/xmtp-web/tree/main/packages/react-sdk#install) section in the React SDK README for a command that will install everything you need.

**Comment by happyeric77** [comment]
Got it!! Thank you @rygine.
Just being curious, as far as my understanding is correct, all of those peer dependencies are from `xmtp`. What makes it more preferable as `peerDependencies over` `dependencies`??

**Comment by rygine** [comment]
since the React SDK is a library to be used by apps, the peer dependencies are meant to inform developers that certain other library versions are required. most package managers will warn when the requirements aren't met. this gives developers more control to choose their own version of the package that fits these constraints. it also aims to prevent any potential conflicts with having multiple versions of the same dependency present.

hope that helps!

**Comment by eric-notifi** [comment]
@rygine Thanks! that makes sense. 
One more question, in the doc, I can see we only need to install 4 extra xmtp related packages (@xmtp/xmtp-js @xmtp/content-type-reaction @xmtp/content-type-remote-attachment @xmtp/content-type-reply).
However, I can see there is one more xmtp package listed in `xmtp/react-sdk` peerDependencies as below:
```json
"peerDependencies": {
    "@xmtp/content-type-primitives": "^1.0.1",
    // Others ...    
  },
```
Wondering do we also need to install this one?

**Comment by rygine** [comment]
good catch! it's also listed under `dependencies` so you won't need to manually install that one for now. i should move it and `@xmtp/content-type-text` under `peerDependencies` at some point.
