### ISSUE TITLE
Bug: @xmtp/react-sdk useLastMessage hook missed

### ISSUE THREAD

**Issue by jsonpreet** [xmtp/xmtp-web#53]
### Describe the bug

useLastMessage hook is missed in given package

Code is following from xmtp-web/examples

https://github.com/xmtp/xmtp-web/blob/main/examples/react-quickstart/src/components/ConversationCard.tsx

package: @xmtp/react-sdk: 1.0.0-preview.40

**Comment by rygine** [comment]
with the official production release this week, the `useLastMessage` hook should be present in the package (`v1.0.0`+). please let me know otherwise.
