### ISSUE TITLE
Bug: Next js support

### ISSUE THREAD

**Issue by asooge** [xmtp/xmtp-web#83]
### Describe the bug

Using next js v13.4.0. Having a build failure due to :
```
SyntaxError: Named export 'Client' not found. The requested module '@xmtp/xmtp-js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@xmtp/xmtp-js';
const { ContentTypeText, ContentTypeId, Client, SortDirection, decodeContent } = pkg
```

I'm on the latest version: "@xmtp/react-sdk": "1.3.4"
We have implemented an early version using "@xmtp/xmtp-js": "7.13.0" and trying to refactor/migrate to the react sdk which looks great. Does the sdk support/been tested in a next js app? Could it be something wrong with my configuration?

App is wrapped with XMTPProvider: 
```ts
import { XMTPProvider } from "@xmtp/react-sdk";`
```

I am importing hooks like:
```ts
import { useClient, useConversations } from "@xmtp/react-sdk";
```

![image](https://github.com/xmtp/xmtp-web/assets/34760728/2784da47-4e6e-46e6-900b-5e547b401e0e)

### Expected behavior

build success

### Steps to reproduce the bug

- next js v13.4.0
- @xmtp/react-sdk v1.3.4
- configure XMTPProvider and import `useClient`, `useConversations`
- run `build`

**Comment by rygine** [comment]
hey @asooge! thanks for the report. do you have `type: "module"` set in your `package.json` file? if not, try that.

**Comment by asooge** [comment]
thanks for the quick reply @rygine! I tried configuring as `type: "module"` but did not fix the error.

Seems to be coming from the next server side when generating static pages. for example: `Error occurred prerendering page "/profile". Read more: https://nextjs.org/docs/messages/prerender-error`

**Comment by rygine** [comment]
hmm, ok. i think what's happening is that Next.js is trying to import the CommonJS version of `@xmtp/xmtp-js` from the ESM version of `@xmtp/react-sdk`, which is clearly an issue. i believe in the past i had to enable experimental ESM support in Next.js, but that was months ago.

are you using `import` statements throughout? is there a code repository i could review?
